# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---
- name: Validate bundle
  local_action: shell behave bundle.feature -D node={{ inventory_hostname }} -D c_lang={{ ansible_network_os }} -D stage={{ stage }} --no-capture -c
  args:
    chdir: roles/topology/files/features/
  register: test_output
  listen: bundle
  
- name: Print testresults
  debug: 
    var: test_output.stdout_lines
  failed_when: "'Assertion Failed' in test_output.stdout"
  listen: bundle
...