# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---
p: true
pe: true
AS: 65100
rr1: 192.168.255.1
rr2: 192.168.255.2
...
